# Generated by Django 3.1.7 on 2021-03-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0007_auto_20210228_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='special_notes',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
