# Generated by Django 3.1.7 on 2021-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0008_auto_20210321_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(default=None, max_length=25)),
                ('customer_name', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
